## **Appliances Recommendation System**

##### **Content Based and Popularity Based**

In [1]:
import pandas as pd

In [2]:
products= pd.read_csv("All Appliances-Copy1.csv")
products.head(2)

,name,main_category,sub_category,image,link,ratings,no_of_ratings,discount_price,actual_price
0,Pigeon by Stovekraft Amaze Plus Electric Kettl...,appliances,All Appliances,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/Pigeon-Amaze-Plus-1-5-Lt...,3.9,"128,941",₹599,"₹1,245"
1,Pigeon Polypropylene Mini Handy and Compact Ch...,appliances,All Appliances,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/Pigeon-Stovekraft-Plasti...,4.1,"274,505",₹199,₹545

In [3]:
products.shape

(9576, 9)

In [4]:
products.duplicated().any()

np.False_

In [5]:
products.isna().sum()

name                0
main_category       0
sub_category        0
image               0
link                0
ratings           478
no_of_ratings     478
discount_price    362
actual_price       91
dtype: int64

In [6]:
products.dtypes

name              object
main_category     object
sub_category      object
image             object
link              object
ratings           object
no_of_ratings     object
discount_price    object
actual_price      object
dtype: object

In [7]:
integers = ["ratings", "no_of_ratings", "discount_price", "actual_price"]
for i in integers:
    products[i] = pd.to_numeric(products[i], errors = "coerce")

## Popularity Based Recommendation System

In [8]:
avg_ratings = products.groupby("name")["ratings"].mean().reset_index()
avg_ratings.rename(columns={"ratings":"avg_ratings"}, inplace=True)

In [9]:
combine = avg_ratings.merge(products, on = "name").drop_duplicates()[["name", "main_category", "sub_category", "image", "link", "no_of_ratings", "avg_ratings"]]

In [10]:
combine

,name,main_category,sub_category,image,link,no_of_ratings,avg_ratings
0,""" SF-400A"" ,10kg x 1gm kitchen weighing scale ...",appliances,All Appliances,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/SF-400A-weighing-Electro...,NaN,NaN
1,"""A"" PLUS Hygiene Portable Room Air Purifier an...",appliances,All Appliances,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/Hygiene-Portable-Humidif...,911.0,4.100000
2,(26.4 cm / 10.3 Inches) Samsung Semi Automatic...,appliances,All Appliances,https://m.media-amazon.com/images/I/610hQiWTE9...,https://www.amazon.in/Samsung-Automatic-Washin...,5.0,4.300000
3,(26.4 cm / 10.3 Inches) Samsung Semi Automatic...,appliances,All Appliances,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/Samsung-Automatic-Washin...,10.0,3.366667
4,(26.4 cm / 10.3 Inches) Samsung Semi Automatic...,appliances,All Appliances,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/Samsung-Automatic-Washin...,2.0,3.366667
...,...,...,...,...,...,...,...
9571,"yalli SUN Instant Running ABS Plastic, Auto Cu...",appliances,All Appliances,https://m.media-amazon.com/images/I/71XttQKU9i...,https://www.amazon.in/yalli-SUN-Instant-Water-...,44.0,3.900000
9572,"yeedi Vac 2 Robot Vacuum Cleaner with Mopping,...",appliances,All Appliances,https://m.media-amazon.com/images/I/71FXlyhZR5...,https://www.amazon.in/yeedi-Cleaner-Mopping-Ob...,NaN,4.300000
9573,zensat Portable USB Juicer Electric USB Juice ...,appliances,All Appliances,https://m.media-amazon.com/images/I/51ljw0TZGc...,https://www.amazon.in/zensat-Portable-Electric...,7.0,4.800000
9574,"® 6 Inch Spun Filter for Pureit Classic RO+MF,...",appliances,All Appliances,https://m.media-amazon.com/images/I/21J8mZwdmR...,https://www.amazon.in/Inch-Spun-Filter-Pureit-...,2.0,4.600000
9575,"® 6 Inch Spun Filter for Pureit Classic RO+MF,...",appliances,All Appliances,https://m.media-amazon.com/images/I/21J8mZwdmR...,https://www.amazon.in/Inch-Spun-Filter-Pureit-...,2.0,4.600000

In [11]:
popular_appliances = combine[combine["no_of_ratings"]>250].sort_values("avg_ratings", ascending = False).head(50)
popular_appliances.head()

,name,main_category,sub_category,image,link,no_of_ratings,avg_ratings
574,Aeropress Coffee Maker,appliances,All Appliances,https://m.media-amazon.com/images/I/31bUKPqr4n...,https://www.amazon.in/Aeropress-Coffee-Maker/d...,257.0,4.8
4231,"Jimmy JV35 Mattress Vacuum Cleaner, 700W Anti ...",appliances,All Appliances,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/Jimmy-JV35-Mattress-Ster...,832.0,4.7
5041,Lifestraw Peak Series Personal Water Filter St...,appliances,All Appliances,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/LifeStraw-Peak-Filtratio...,609.0,4.7
4794,"Kuvings Nutri Blender PRO Ferrari Red, Powerfu...",appliances,All Appliances,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/Kuvings-Ferrari-Red-Smoo...,667.0,4.7
4622,Konvio Neer Plastic Tap Suitable For All Ro Wa...,appliances,All Appliances,https://m.media-amazon.com/images/I/71vGuriUAm...,https://www.amazon.in/Plastic-Tap-Suitable-Pur...,396.0,4.7

In [12]:
popular_appliances.shape

(50, 7)

In [13]:
popular_appliances["image"][5041]

'https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/41VvFor1m1L._AC_UL320_.jpg'

## **Content Based Filtering**

In [14]:
products.head(2)

,name,main_category,sub_category,image,link,ratings,no_of_ratings,discount_price,actual_price
0,Pigeon by Stovekraft Amaze Plus Electric Kettl...,appliances,All Appliances,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/Pigeon-Amaze-Plus-1-5-Lt...,3.9,NaN,NaN,NaN
1,Pigeon Polypropylene Mini Handy and Compact Ch...,appliances,All Appliances,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/Pigeon-Stovekraft-Plasti...,4.1,NaN,NaN,NaN

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel

In [16]:
tfidf = TfidfVectorizer(stop_words="english")

In [17]:
products["tags"] = (products["name"] + " " + products["main_category"] + " " + products["sub_category"])

In [18]:
products.head()

,name,main_category,sub_category,image,link,ratings,no_of_ratings,discount_price,actual_price,tags
0,Pigeon by Stovekraft Amaze Plus Electric Kettl...,appliances,All Appliances,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/Pigeon-Amaze-Plus-1-5-Lt...,3.9,NaN,NaN,NaN,Pigeon by Stovekraft Amaze Plus Electric Kettl...
1,Pigeon Polypropylene Mini Handy and Compact Ch...,appliances,All Appliances,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/Pigeon-Stovekraft-Plasti...,4.1,NaN,NaN,NaN,Pigeon Polypropylene Mini Handy and Compact Ch...
2,Glun Multipurpose Portable Electronic Digital ...,appliances,All Appliances,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/Multipurpose-Portable-El...,3.8,365.0,NaN,NaN,Glun Multipurpose Portable Electronic Digital ...
3,beatXP Kitchen Scale Multipurpose Portable Ele...,appliances,All Appliances,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/beatXP-Multipurpose-Port...,3.7,NaN,NaN,NaN,beatXP Kitchen Scale Multipurpose Portable Ele...
4,Bajaj DX-6 1000W Dry Iron with Advance Solepla...,appliances,All Appliances,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/Bajaj-Majesty-1000-Watt-...,4.2,NaN,NaN,NaN,Bajaj DX-6 1000W Dry Iron with Advance Solepla...

In [19]:
tfidf_matrix = tfidf.fit_transform(products["tags"])

In [21]:
def recommend(user_input):
    query_vector = tfidf.transform([user_input])
    cosine_sim = linear_kernel(tfidf_matrix, query_vector)
    sim_score = sorted(list(enumerate(cosine_sim)), key = lambda x:x[1], reverse = True)[1:10]
    sim_index = [i[0] for i in sim_score]

    print(products["tags"].iloc[sim_index])

recommend("appliances")

1851         AIR COOLER TROLLEY appliances All Appliances
2706    Lg water inlet filter for all washing machine ...
8999    Forbes X-1 Star Vacuum Cleaner appliances All ...
4087    Plastic Lid for Sujata (White) appliances All ...
445     Bosch Appliances TrueMixx Pro Mixer Grinder, 7...
4671         Ingco Mini grinder appliances All Appliances
8837    sujata Blade for Grinder Jar appliances All Ap...
2773    ATLAS HOME APPLIANCES High Speed Table Fan for...
6676    Karcher Water Filter for Pressure Washer appli...
Name: tags, dtype: object

In [22]:
import pickle

In [28]:
pickle.dump(popular_appliances, open("popular_appliances.pkl", "wb"))
pickle.dump(tfidf_matrix, open("tfidf_matrix.pkl", "wb"))
pickle.dump(tfidf, open("tfidf.pkl", "wb"))
pickle.dump(products, open("products.pkl", "wb"))